# Generated by Django 6.0.6 on 2026-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
