# Generated by Django 6.1.1 on 2026-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_flashcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
